# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ver1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 350)
        MainWindow.setMinimumSize(QtCore.QSize(100, 100))
        MainWindow.setMaximumSize(QtCore.QSize(800, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.background = QtWidgets.QFrame(self.centralwidget)
        self.background.setMaximumSize(QtCore.QSize(800, 450))
        self.background.setStyleSheet("background-color: rgb(121, 121, 121);")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.sidebar = QtWidgets.QFrame(self.background)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 120, 450))
        self.sidebar.setMinimumSize(QtCore.QSize(100, 350))
        self.sidebar.setMaximumSize(QtCore.QSize(300, 450))
        self.sidebar.setStyleSheet("background-color: rgb(111, 0, 0);")
        self.sidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebar.setObjectName("sidebar")
        self.toggle = QtWidgets.QFrame(self.sidebar)
        self.toggle.setGeometry(QtCore.QRect(0, 0, 120, 80))
        self.toggle.setMinimumSize(QtCore.QSize(120, 80))
        self.toggle.setMaximumSize(QtCore.QSize(100, 80))
        self.toggle.setStyleSheet("border-color: rgb(18, 18, 18);\n"
"background-color: rgb(186, 0, 0);")
        self.toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toggle.setObjectName("toggle")
        self.pushButton = QtWidgets.QPushButton(self.sidebar)
        self.pushButton.setGeometry(QtCore.QRect(20, 110, 75, 23))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(86, 86, 86);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.sidebar)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 160, 75, 23))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(86, 86, 86);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.topbar = QtWidgets.QFrame(self.background)
        self.topbar.setGeometry(QtCore.QRect(120, 0, 800, 50))
        self.topbar.setMinimumSize(QtCore.QSize(800, 50))
        self.topbar.setMaximumSize(QtCore.QSize(800, 50))
        self.topbar.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.topbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topbar.setObjectName("topbar")
        self.frame_pages = QtWidgets.QFrame(self.background)
        self.frame_pages.setGeometry(QtCore.QRect(120, 50, 780, 450))
        self.frame_pages.setMinimumSize(QtCore.QSize(780, 450))
        self.frame_pages.setMaximumSize(QtCore.QSize(780, 450))
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, -1, 780, 450))
        self.stackedWidget.setMinimumSize(QtCore.QSize(780, 450))
        self.stackedWidget.setMaximumSize(QtCore.QSize(780, 450))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("background-color: rgb(0, 125, 193);")
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("background-color: rgb(0, 188, 103);")
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.background)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
